### ISSUE TITLE
Apparent infinite indexing loop

### ISSUE THREAD

**Issue by jmellor** [yuri-karpovich/geminabox#1]
We had our spoonest/geminabox service unexpectedly go down last night, in a 100% processor utilization loop in the unicorn docker image.  It was a snapshot from 13months ago.  It is running on a Ubuntu-16 host with 3GB RAM (with slight paging), 1 cpu and has plenty of disk available.

There are no releases for this project, so I upgraded to latest this morning, and while I now have different internal symptoms in docker logs, it has locked up again after about an hour.

The docker logs output seems to show that "Marshall quick index gemspecs" is looping continuously.  I am unsure if there is a design error with it seeing a gem that the indexing is unable to handle, or it is a coding error.  Help!

Log excerpt attached.

[geminabox.log.zip](https://github.com/yuri-karpovich/geminabox/files/1300095/geminabox.log.zip)

**Comment by jmellor** [comment]
Attached is a graph of memory usage over the last 2 months, clearly showing a major application malfunction/leak.
![screen shot 2017-09-13 at 2 38 18 pm](https://user-images.githubusercontent.com/11075941/30396109-7fd4da68-9896-11e7-946f-1ee9e1cd1198.png)

**Comment by yuri-karpovich** [comment]
@jmellor 
Sad to hear that. I'm not a developer of [Geminabox](https://github.com/geminabox/geminabox) gem but you're right I'm responsible for the Docker image you are using. I've updated image with the latest version of geminabox. Please try it with `spoonest/geminabox:0.13.5` image. I will dig into the code deeper then but I hope it will help you. 

Btw, 
how long have you used it before it crashed? 
do you have large-size gems?
did you use RUBYGEMS_PROXY?

**Comment by jmellor** [comment]
Yuri asked:
> how long have you used it before it crashed?

It has been in operation with no known alterations for 13 months. In that time, it has accumulated 2276 gems in the repo. Per the steadily-increasing memory size chart that I uploaded to the ticket, it may have been doing something wrong for the last 14 days, and just hit a wall of some kind.

> do you have large-size gems?

Nokogiri is just under 10MB in size. There are a number of 9MB gems like zookeeper and bson, and then smaller ones.

> did you use RUBYGEMS_PROXY?

No.

On Wed, 2017-09-13 at 13:10 -0700, Yuri Karpovich wrote:

@jmellor<https://github.com/jmellor>
Sad to hear that. I'm not a developer of Geminabox<https://github.com/geminabox/geminabox> gem but you're right I'm responsible for the Docker image you are using. I've updated image with the latest version of geminabox. Please try it with spoonest/geminabox:0.13.5 image. I will dig into the code deeper then but I hope it will help you.

Btw,
how long have you used it before it crashed?
do you have large-size gems?
did you use RUBYGEMS_PROXY?

**Comment by yuri-karpovich** [comment]
Ok. Please test  `spoonest/geminabox:0.13.5` release and then we'll see.

**Comment by jmellor** [comment]
Yuri wrote:
> Ok. Please test spoonest/geminabox:0.13.5 release and then we'll see.

Updated and restarted. It appears to be running correctly, and much faster than it ran previously. I have only pulled through its upstream cache at this point, and not pushed a gem to it yet. I have not seen it re-index yet.

Not knowing what went wrong, I cannot say that it will not fall over again, but keeping my fingers crossed. I'll update you sometime tomorrow, ok?

**Comment by yuri-karpovich** [comment]
Glad to hear it. And by the way that image is running under WEBrick. I've created new one `spoonest/geminabox:0.13.5-puma` which runs under Puma server . Hope it will be even faster :)

**Comment by jmellor** [comment]
After 18hrs of monitoring the new image, I am confident that it will stay up for a long period.
I was initially concerned about the memory utilization curve with the new image, but have observed the ubuntu+docker+image memory utilization grow from ~2.4GB and stabilize at ~3.4GB, presumably due to normal heap and disk cache usage.
Closing.  The problem in the 13month-old docker image remains unknown and possibly was a bug in geminabox that has been resolved with the new docker image now using the newer geminabox version.

**Comment by jmellor** [comment]
FYI, I found the root-cause of the geminabox problem.

Upstream has a defective gem somehow. When that gem is downloaded, gem generate_index stops working, and geminabox malfunctions.

Unfortunately I do not know which gem is defective, as I deleted 1400 gems from the geminabox gems directory before the problem was resolved. The best that I can narrow it down to is a bad gem somewhere between aaa* and aaz*.

--
Regards,
John Mellor, esentire


On Wed, 2017-09-13 at 17:42 -0400, esentire\jmellor wrote:
Yuri wrote:
> Ok. Please test spoonest/geminabox:0.13.5 release and then we'll see.

Updated and restarted. It appears to be running correctly, and much faster than it ran previously. I have only pulled through its upstream cache at this point, and not pushed a gem to it yet. I have not seen it re-index yet.

Not knowing what went wrong, I cannot say that it will not fall over again, but keeping my fingers crossed. I'll update you sometime tomorrow, ok?

**Comment by yuri-karpovich** [comment]
Sorry to hear that the issue was reproduced again. I've started my geminabox container right after our previous discussion and it's still working stable. But I have really small amount of gems in it (about 500). It seems to be [geminabox](https://github.com/geminabox/geminabox) issue, you should submit it to them and probably there is anyone who had similar issue before.

**Comment by jmellor** [comment]
On Tue, 2017-10-03 at 14:11 -0700, Yuri Karpovich wrote:

Sorry to hear that the issue was reproduced again. I've started my geminabox container right after our previous discussion and it's still working stable. But I have really small amount of gems in it (about 500). It seems to be geminabox<https://github.com/geminabox/geminabox> issue, you should submit it to them and probably there is anyone who had similar issue before.

I have submitted geminabox issues 285 (Add reasonableness check to the gem install pull) and 286 (Fix indexing infinite recursion), and hopefully geminabox will be fixed rsn to handle this scenario...

**Comment by jmellor** [comment]
On Tue, 2017-10-03 at 14:11 -0700, Yuri Karpovich wrote:

Sorry to hear that the issue was reproduced again. I've started my geminabox container right after our previous discussion and it's still working stable. But I have really small amount of gems in it (about 500). It seems to be geminabox<https://github.com/geminabox/geminabox> issue, you should submit it to them and probably there is anyone who had similar issue before.

Naotoshi Sao said:
> 1. Number of web concurrency can be controlled by your server, like 4 concurrent processes with unicorn server.
> 2. reindex should not be ran concurrently now https://github.com/geminabox/geminabox/pull/276/files. Do you use the latest version and do you still get multiple reindexes concurrently?
. . .
> The latest is 0.13.9. The fix to serialize reindexing was added in 0.13.8

All tagged variants of the docker image are pulling down geminabox 0.13.5. Master and test are pulling 0.13.4 version. Is it possible to move up to 0.13.9 release?

**Comment by yuri-karpovich** [comment]
Sure. I will update the image tonight.

**Comment by yuri-karpovich** [comment]
@jmellor please try `spoonest/geminabox:puma-0.13.9`. Sorry, I have no time to test it right now so I hope it works.

**Comment by yuri-karpovich** [comment]
@jmellor have you tried it?

**Comment by jmellor** [comment]
On Wed, 2017-10-04 at 18:05 +0000, Yuri Karpovich wrote:

@jmellor<https://github.com/jmellor> please try spoonest/geminabox:puma-0.13.9. Sorry, I have no time to test it right now so I hope it works.

Sorry for the delay - I had to clone the gem repo machine to test outside of production.
The web page works, and seems faster than the 0.13.5 version. Gem installs work, but deletes stall and then give a 500 error. The older image was also very slow deleting a geming, but did not fail.

**Comment by yuri-karpovich** [comment]
I cannot reproduce 500 issue on delete action. I guess the issue is related to server settings. You have a lot of gems and server may down because of timeout issues.  `*-0.13.9` images were configured to start with default server settings. I've added an ability to use own server configs for `puma-0.13.9.001` and `unicorn-0.13.9.001` images. To do it you can mount folder with config with `-v /path_to_folder_with_config.ru:/webapps/server/config` option. 
I'm not sure it will fix your issue but I have increased default timeouts from 60s to 120s. Anyway you can try to set timeout values through `config.ru`.
